version: "3"
services:
  schulcast:
    container_name: schulcast
    image: schulcast:latest
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:80
      - JWT_SECRET=${JWT_SECRET}
      - BASE_URL=${BASE_URL}
    volumes:
      - "~/schulcast/uploads:/server/uploads"
      - "~/schulcast/database:/server/database"

  schulcast-podcast-manager:
    container_name: schulcast-podcast-manager
    image: vonproteus/podcast-generator:v3.1.1
    restart: always
    volumes:
     - ~/schulcast/podcast:/app/PodcastGenerator/appdata

networks:
  default:
    name: nginx
    external: true
