version: "3"
services:
  schulcast:
    container_name: schulcast
    image: schulcast:latest
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:80
      - JWT_SECRET=${JWT_SECRET}
      - BASE_URL=${BASE_URL}
    volumes:
      - "~/schulcast/uploads:/server/uploads"
      - "~/schulcast/database:/server/database"

networks:
  default:
    name: nginx
    external: true
