import '@a11d/lit-slider'
import '@a11d/lit-application'
import '@a11d/lit-application-native'
import '@3mo/model'
import './Schulcast'
import './components'
import './dialogs'
import './pages'