name: Compose Up

on:
  workflow_dispatch:

jobs:
  Restart:
    name: ⬆️ Up
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ./schulcast/.build
            export JWT_SECRET=${{ secrets.JWT_SECRET }}
            export COMPOSE_PROJECT_NAME=schulcast
            docker-compose -f ./docker-compose.prod.yml up -d