name: Compose Down

on:
  workflow_dispatch:

jobs:
  Restart:
    name: ⬇️ Down
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ./schulcast/.build
            export DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            export JWT_SECRET=${{ secrets.JWT_SECRET }}
            export COMPOSE_PROJECT_NAME=schulcast
            export GOOGLE_CREDENTIALS_JSON=$'${{ secrets.GOOGLE_CREDENTIALS_JSON }}'
            export ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
            docker-compose -f ./docker-compose.prod.yml down