name: Compose Restart

on:
  workflow_dispatch:

jobs:
  Restart:
    name: 🔄️ Restart
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ./schulcast/.build
            export JWT_SECRET=${{ secrets.JWT_SECRET }}
            export COMPOSE_PROJECT_NAME=schulcast
            docker-compose -f ./docker-compose.prod.yml down
            docker-compose -f ./docker-compose.prod.yml up -d