name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -f ./Dockerfile --tag schulcast:latest .
      - run: docker save schulcast:latest -o schulcast.image
      - run: |
          mkdir -p ./artifacts
          mv schulcast.image ./artifacts/schulcast.image
          mv compose.prod.yml ./artifacts/compose.yml
      - uses: up9cloud/action-rsync@v1.4
        env:
          SOURCE: ./artifacts/
          TARGET: ~/schulcast/.build
          KEY: ${{secrets.SSH_KEY}}
          HOST: ${{secrets.DEPLOY_SERVER_SSH_HOST}}
          PORT: ${{secrets.DEPLOY_SERVER_SSH_PORT}}
          USER: ${{secrets.DEPLOY_SERVER_SSH_USERNAME}}
          VERBOSE: true

  Deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs:
      - Build
    steps:
        - uses: appleboy/ssh-action@v0.1.4
          with:
            key: ${{secrets.SSH_KEY}}
            host: ${{secrets.DEPLOY_SERVER_SSH_HOST}}
            port: ${{secrets.DEPLOY_SERVER_SSH_PORT}}
            username: ${{secrets.DEPLOY_SERVER_SSH_USERNAME}}
            script: |
              cd ./schulcast/.build
              export JWT_SECRET=${{secrets.JWT_SECRET}}
              export COMPOSE_PROJECT_NAME=schulcast
              docker load -i ./schulcast.image
              podman-compose up -d
              docker exec nginx service nginx reload