name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -f ./Dockerfile.prod --tag schulcast:latest .
      - run: docker save schulcast:latest -o schulcast_image
      - uses: actions/upload-artifact@v3
        with:
          path: schulcast_image
          name: schulcast_image

  Deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs:
      - Build
    steps:
        - uses: actions/checkout@v3

        - uses: actions/download-artifact@v3
          with:
            name: schulcast_image

        - uses: appleboy/scp-action@v0.1.4
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: ${{ secrets.SSH_PORT }}
            source: "schulcast_image,docker-compose.prod.yml"
            target: "~/schulcast/.build"
            overwrite: true

        - uses: appleboy/ssh-action@v0.1.4
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_PASSWORD }}
            port: ${{ secrets.SSH_PORT }}
            script: |
              cd ./schulcast/.build
              export JWT_SECRET=${{ secrets.JWT_SECRET }}
              export COMPOSE_PROJECT_NAME=schulcast
              docker load -i ./schulcast_image
              docker-compose -f ./docker-compose.prod.yml up -d